### PR TITLE
fix ristretto encoding issues

### PR DESCRIPTION
**Pull request by TerenceGe**

### CODE REVIEW

**Comment by burdges** [comment]
Is this fixing #1 then?

**Comment by TerenceGe** [comment]
@burdges you can try the testing, encoding basepoint is passed.  There seems some bugs in the testing code which make test_ristretto_encode_small_multiples_of_basepoint function failed. But it's not related to the encoding feature. I  can fix the testing code in a new pr if you want to see.

**Review by isislovecruft — COMMENTED** [review]
Hi! Thanks for the patch. This doesn't seem to fix the tests not matching the vectors however:

```
invsqrt test: OKAY invsqrt computed correctly with tweak=1                            
test 32 byte array equality (0==0): OKAY
test 32 byte array equality (0==1): OKAY
decoding random invalid point: OKAY
decoding basepoint: OKAY
expanding and contracting random field element: OKAY
expanding and contracting basepoint: OKAY
test expanding and contracting additive identity: OKAY                                    
test unpacking and packing a group element: OKAY
test ristretto encode identity: OKAY                                                  
test ristretto encode basepoint: FAIL
encoding small multiples of basepoint:                                                    
  - FAIL small multiple #1 failed to encode correctly
  - FAIL small multiple #2 failed to encode correctly
  - FAIL small multiple #3 failed to encode correctly
  - FAIL small multiple #4 failed to encode correctly
  - FAIL small multiple #5 failed to encode correctly
  - FAIL small multiple #6 failed to encode correctly                                 
  - FAIL small multiple #7 failed to encode correctly
  - FAIL small multiple #8 failed to encode correctly
  - FAIL small multiple #9 failed to encode correctly
  - FAIL small multiple #10 failed to encode correctly
  - FAIL small multiple #11 failed to encode correctly                         
  - FAIL small multiple #12 failed to encode correctly
  - FAIL small multiple #13 failed to encode correctly
  - FAIL small multiple #14 failed to encode correctly                              
  - FAIL small multiple #15 failed to encode correctly                   
test ristretto constant time equality check: OKAY                                      
```

I would highly advise against using the current form of this code in any project.

**Comment by isislovecruft** [comment]
Hi @TerenceGe, would you be willing to share the changes to the testing code? I'd like to make sure that the encoding matches the other implementations we have before anyone starts using it.

**Comment by TerenceGe** [comment]
Screen Shot 2020-09-24 at 12 11 07 AM

Hello, @isislovecruft. Just changed some testing code and it's running correctly in my mac, but I have't test it in windows yet.

**Pull request merged**
